// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADlbiIr8yqT_YfjBnmCLdMtyP4keGFZHU',
    appId: '1:266755968373:web:4c4aa606ff4bade61f173c',
    messagingSenderId: '266755968373',
    projectId: 'burgerexpress-25634',
    authDomain: 'burgerexpress-25634.firebaseapp.com',
    storageBucket: 'burgerexpress-25634.firebasestorage.app',
    measurementId: 'G-N3G345BFFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRImdXqR6YyBcqTIP_wgZCpGL_wvNobCU',
    appId: '1:266755968373:android:20746345141bad731f173c',
    messagingSenderId: '266755968373',
    projectId: 'burgerexpress-25634',
    storageBucket: 'burgerexpress-25634.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRgTdHSxuWiJChNOYQD-ODy9CGF1H5Urs',
    appId: '1:266755968373:ios:901d406ca2cf9be71f173c',
    messagingSenderId: '266755968373',
    projectId: 'burgerexpress-25634',
    storageBucket: 'burgerexpress-25634.firebasestorage.app',
    iosBundleId: 'com.example.burgerexpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRgTdHSxuWiJChNOYQD-ODy9CGF1H5Urs',
    appId: '1:266755968373:ios:901d406ca2cf9be71f173c',
    messagingSenderId: '266755968373',
    projectId: 'burgerexpress-25634',
    storageBucket: 'burgerexpress-25634.firebasestorage.app',
    iosBundleId: 'com.example.burgerexpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADlbiIr8yqT_YfjBnmCLdMtyP4keGFZHU',
    appId: '1:266755968373:web:fda7c5f80b0f0f2a1f173c',
    messagingSenderId: '266755968373',
    projectId: 'burgerexpress-25634',
    authDomain: 'burgerexpress-25634.firebaseapp.com',
    storageBucket: 'burgerexpress-25634.firebasestorage.app',
    measurementId: 'G-H5VLTS1X6F',
  );
}
